### ISSUE TITLE
Suggestion for processing

### ISSUE THREAD

**Issue by ehenneken** [adsabs/metrics_service#143]
Does it make sense to explore the implementation of Celery queues for the various tasks (calculating the various components)

**Comment by seasidesparrow** [comment]
Celery makes sense if parallelization makes sense.  If you have to gather results to do a final calculation, you have to ensure you have all results completed before you execute the final step.  But otherwise, if you have tasks that do one thing with one object and have to do that for many objects, dividing up the work among multiple workers makes sense.
