### ISSUE TITLE
difference with BEER metrics

### ISSUE THREAD

**Issue by ehenneken** [adsabs/metrics_service#53]
Citation metrics the `author:"Accomazzi,A"` are different in BEER

**Comment by aholachek** [comment]
the read10 index is also different, at least for alberto

**Comment by ehenneken** [comment]
I guess I'm also allowing the possibility that BEER is wrong... after all, I have extensive unittests for all functionality in my web service and there are none in BEER...

**Comment by aholachek** [comment]
it seems that at least some of the issue is with the current version:

for 181 returned papers for Alberto you get:

"citation stats": {
    "average number of citations": 5.415384615384616,
    "average number of refereed citations": 2.5692307692307694,
    "median number of citations": 3.0,
    "median number of refereed citations": 1.0,
    "normalized number of citations": 68.63843101343102,
    "normalized number of refereed citations": 30.591941391941397,
    "number of citing papers": 181,
    "number of self-citations": 157,
    "total number of citations": 352,
    "total number of refereed citations": 167
  },

352 total citations /181 total papers = 1.94

In beer, the average number of citations for this same data is 2; whereas
in the new version it is 5.4

Maybe I am confused?

**Comment by ehenneken** [comment]
I'm starting to wonder if 5.4 is the average over citations unequal to zero... :-) Papers without citations obviously contribute to the average too ;-)

**Comment by ehenneken** [comment]
I'll look into this on Monday
