### ISSUE TITLE
REST-API improvements

### ISSUE THREAD

**Issue by vsudilov** [adsabs/metrics_service#61]
Hi,

What about refactoring the API to follow a pattern like this:

`curl metrics/:type -d ['bibcode1'...]`

That would mean
  - No need to define other parameters in the post body, which is not really transparent 
  - (Potentially, but not necessarily) deprecate the metrics/:bibcode endpoint

That seems more "RESTful" to me than having a single endpoint that is controlled by a POST body. Thoughts?

**Comment by ehenneken** [comment]
Hi Vlad

Having thought about this a bit longer, I don't think this is going to work (at least not elegantly). How would you capture the request "for these bibcodes, give me basic stats and the reads and citation histograms"? Something like

  `curl metrics/basic,histograms/reads,citations -d ['bibcode1'...]`

or something similar? Even though we haven't really implemented this (yet), the metrics service supports getting the metrics for a query (e.g. get metrics for "orcid:0000-0003-4264-2450"), but I suppose the query would go into the POST body, instead of the bibcodes. You think a URL like

   `curl metrics/basic,citations,histograms,indicators,timeseries/publications,reads,citations -d ['bibcode1'...]`

(which would be the necessary URL to omit the downloads histograms) would be preferable over querying with the parameters in the POST body (in which case you could omit the metrics types)? Of course, I could add a type 'all' to replace 'basic,citations,histograms,indicators,timeseries' if all metrics types are required, but not all histogram flavors.

**Comment by vsudilov** [comment]
I don't think we want support getting mertics from a query -- this blurs the lines between search and metrics and introduces mutual API dependence.

Clearly we shouldn't use commas in URLs; it still seems however like we can/should strive for making the API a bit easier to grok, especially since it is a user facing interface.

**Comment by ehenneken** [comment]
I would be trivial to let a URL like

`curl metrics/bchit/prc -d ['bibcode1'...]`

do the same as the last one with the commas above. Not very intuitive, though :-)

**Comment by vsudilov** [comment]
Ok, now from the opposite perspective: what is the benefit from specifying these things? ie, why not just a single endpoint that takes a list of bibcodes and gives the user all metricsy results:

`curl -d ['b1',...] http://metrics`

**Comment by ehenneken** [comment]
Isn't that what the current service already provides? :-)

**Comment by vsudilov** [comment]
Sort of, and that's how I'm treating it for the purposes of the python client, too. Would it be fine to simplify the post body to just a list of bibcodes then?

**Comment by romanchyla** [comment]
I thought metrics relies on solr for getting data so this dependency is tight, but i could be having outdated information (?)

btw: when you **have to make the POST request** anyway, machines would probably prefer the configurable post over the the long url string with position encoded parameters

```
curl http://metrics/basic,for,bar/hey,joe -d ['b1', ...] 
curl http://metrics/ {type: 'basic', metrics: 'for', payload: ['b1', .....]} 
```

somewhat related #62 -- if we remove the ability to send a query and request metrics for it, we'll probably need to expose this functionality through some other 'auxiliary service' -- cause bbb would have to harvest 300 papers in order to send them to metrics; this will be slowing down the clients

**Comment by ehenneken** [comment]
1. The POST body can have just a list of bibcodes, like the example in the README (no need to further specification of other parameters)

2. I'll remove the 'query' part of the metrics, or at least disable it

**Comment by vsudilov** [comment]
Thanks for considering how to make the API more intuitive with me.
